name: Release
on:
  pull_request:
    branches: [main]
    types: [closed]
permissions: write-all
jobs:
  release:
    if: github.event.pull_request.merged == true && github.head_ref == 'autoupdate'
    runs-on: ubuntu-slim
    steps:
      - name: Get version
        id: version
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          VERSION="${TITLE#Update to v8 }"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Get artifacts run
        id: ci_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=$(gh api "repos/${{ github.repository }}/actions/workflows/ci.yml/runs?head_sha=${{ github.event.pull_request.head.sha }}&status=success&per_page=1" --jq '.workflow_runs[0].id')
          if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
            echo "you merged a PR with a failed CI run lol"
            exit 1
          fi
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v8
        with:
          run-id: ${{ steps.ci_run.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: artifacts/
          merge-multiple: true
      - uses: actions/checkout@v6
      - name: Create and push tag
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          files: artifacts/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
